baseURL: http://jdanker.com/
languageCode: en-us
title: Jahred Danker
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

menu:
      main:
        - name: About
          url: about
          weight: 1
        - name: Thoughts
          url: thoughts
          weight: 2
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10

params:
    env: production
    ShowShareButtons: true
    defaultTheme: "auto"
    # profile mode 
    profileMode:
        enabled: true
        title: "Jahred Danker" # optional default will be site title
        subtitle: "DevOps Engineer"
        #imageUrl: "<image link>" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
    socialIcons:
      - name: linkedin
        url: "https://linkedin.com/in/jahred"
      - name: github
        url: "https://github.com/jdanker"
      - name: twitter
        url: "https://twitter.com/jahred01"
