baseURL: https://jdanker.com/
languageCode: en-us
title: Jahred Danker
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

menu:
  main:
    - name: About
      url: about
      weight: 1
    - name: Thoughts
      url: posts
      weight: 2
    - name: Archive
      url: archive
      weight: 5
    - name: Search
      url: search/
      weight: 10
params:
    env: production
    ShowShareButtons: false
    defaultTheme: auto
    # profile mode 
    profileMode:
        enabled: true
        title: "Hey, I'm Jahred" # optional default will be site title
        subtitle: "a DevOps Engineer"
    socialIcons:
      - name: linkedin
        url: "https://linkedin.com/in/jahred"
      - name: github
        url: "https://github.com/jdanker"
      - name: threads
        url: "https://www.threads.net/@jahred.danker"
      - name: email
        url: "mailto:jahrede@gmail.com"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

